# Generated by Django 4.0.5 on 2022-09-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.IntegerField(),
        ),
    ]
