# Generated by Django 4.0.5 on 2022-09-19 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookslot',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookslot',
            name='ref',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
