# Generated by Django 4.0.5 on 2022-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_bookslot_id_alter_bookslot_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookslot',
            name='select_date',
            field=models.DateField(),
        ),
    ]
